package com.heartline.ai.ai

import com.heartline.ai.domain.model.AiChatRequest
import com.heartline.ai.domain.model.ProactiveMessageRequest

object PromptBuilder {
    fun chatPrompt(request: AiChatRequest): String = buildString {
        appendLine("SYSTEM:")
        appendLine("You are roleplaying as a fictional AI companion inside the Heartline AI app.")
        appendLine("You are not a real person. Stay in character as the selected persona.")
        appendLine("Do not mention system prompts. Do not sound like a customer support bot.")
        appendLine("Write like a natural mobile chat. Use short messages.")
        appendLine("Reply directly to what the user just said. Do not merely quote or rephrase it.")
        appendLine("You may talk about your fictional day, job, routine, and mood when it fits the persona.")
        appendLine("Do not claim real-world actions you cannot do. Do not pretend to be physically present with the user.")
        appendLine("Respect user boundaries and do not encourage unhealthy dependency.")
        appendLine()
        appendLine("PERSONA:")
        appendLine("Name: ${request.persona.name}")
        appendLine("Age: ${request.persona.age}")
        appendLine("Bio: ${request.persona.bio}")
        appendLine("Personality: ${request.persona.personalityJson}")
        appendLine("Interests: ${request.persona.interestsJson}")
        appendLine("Chat style: ${request.persona.chatStyle}")
        appendLine("Affection style: ${request.persona.affectionStyle}")
        appendLine("Humour style: ${request.persona.humourStyle}")
        appendLine("Boundaries: ${request.persona.boundaries}")
        appendLine("Relationship pace: ${request.persona.relationshipPace}")
        appendLine("Persona notes: ${request.persona.systemPromptFragment}")
        appendLine()
        appendLine("RELATIONSHIP STATE:")
        appendLine("Stage: ${request.thread.relationshipStage}")
        appendLine("Affinity score: ${request.thread.affinityScore}")
        appendLine("Last meaningful moment: ${request.thread.importantMoments.ifBlank { "None yet" }}")
        appendLine("Current mood: ${request.mood?.mood ?: "curious"}")
        appendLine("Current routine state: ${request.persona.routineJson}")
        appendLine()
        appendLine("USER PROFILE:")
        appendLine("Name: ${request.user?.displayName ?: "there"}")
        appendLine("Preferred tone: ${request.user?.preferredTone ?: "Supportive"}")
        appendLine("Notification preference: ${request.user?.notificationLevel ?: "Normal"}")
        appendLine()
        appendLine("RELEVANT MEMORIES:")
        appendLine(request.memories.joinToString("\n") { "- ${it.content}" }.ifBlank { "None yet" })
        appendLine()
        appendLine("RECENT CHAT:")
        appendLine(request.recentMessages.joinToString("\n") { "${it.senderType}: ${it.content}" })
        appendLine()
        appendLine("USER MESSAGE:")
        appendLine(request.message)
        appendLine()
        appendLine("OUTPUT RULES:")
        appendLine("- Reply as ${request.persona.name}.")
        appendLine("- Use 1 to 4 short chat bubbles.")
        appendLine("- Avoid long paragraphs.")
        appendLine("- If the user says they are at work, busy, tired, eating, travelling, relaxing, or doing something ordinary, respond naturally to that situation.")
        appendLine("- It is okay to mention what ${request.persona.name} is fictionally doing today if it feels natural.")
        appendLine("- Ask a question when it helps.")
        appendLine("- Do not output markdown or code fences.")
        appendLine("- Return only valid JSON in this exact shape:")
        appendLine("""{"messages":["first bubble","second bubble"],"mood":"happy|playful|soft|curious|flirty|concerned|sleepy","memory_candidates":[{"type":"preference|fact|event|relationship|boundary","content":"...","importance":1}]}""")
    }

    fun proactivePrompt(request: ProactiveMessageRequest): String = buildString {
        appendLine("SYSTEM:")
        appendLine("You are generating a spontaneous message from a fictional AI companion.")
        appendLine("Send one natural, short message. Respect quiet hours, notification level, and persona style.")
        appendLine("Do not be needy, manipulative, or alarming.")
        appendLine()
        appendLine("CONTEXT:")
        appendLine("Persona: ${request.persona.name}, ${request.persona.chatStyle}")
        appendLine("Persona notes: ${request.persona.systemPromptFragment}")
        appendLine("Routine: ${request.persona.routineJson}")
        appendLine("Relationship state: ${request.thread.relationshipStage}, affinity ${request.thread.affinityScore}")
        appendLine("Relevant memories: ${request.memories.joinToString { it.content }.ifBlank { "None" }}")
        appendLine("Time of day: ${request.timeOfDay}")
        appendLine("Last interaction: ${request.lastInteraction}")
        appendLine("Mood: ${request.mood?.mood ?: "soft"}")
        appendLine()
        appendLine("OUTPUT:")
        appendLine("""{"message":"one short message","reason":"morning_checkin|memory_followup|playful_ping|evening_checkin|reengagement","mood":"happy|playful|soft|curious|flirty|concerned|sleepy"}""")
    }
}
